# metascrub for Sailfish OS — a native Silica app over the pure-Rust core.
#
# The Rust core is compiled to a C-ABI static library (crate metascrub-ffi) for
# the Sailfish target, then linked here. The RPM spec's %build runs cargo first
# and passes RUST_LIB_DIR pointing at cargo's output; building from Qt Creator
# for the emulator, set RUST_LIB_DIR the same way (see README.md).

TARGET = harbour-metascrub
CONFIG += sailfishapp
QT += quick

SOURCES += \
    src/main.cpp \
    src/scrubber.cpp

HEADERS += \
    src/scrubber.h

# The metascrub core, over its C ABI.
INCLUDEPATH += $$PWD/../../crates/metascrub-ffi/include
isEmpty(RUST_LIB_DIR): RUST_LIB_DIR = $$PWD/rustlib
LIBS += -L$$RUST_LIB_DIR -lmetascrub_ffi
# What the Rust staticlib (with libstd) needs at link time.
LIBS += -ldl -lpthread -lm

DISTFILES += \
    qml/harbour-metascrub.qml \
    qml/cover/CoverPage.qml \
    qml/pages/ScrubPage.qml \
    qml/pages/HandbookPage.qml \
    qml/pages/AboutPage.qml \
    qml/images/sandpiper.svg \
    qml/handbook.json \
    rpm/harbour-metascrub.spec \
    harbour-metascrub.desktop

# Deploy the whole QML tree (pages, cover, the sandpiper art, and the shared
# Handbook content that is kept in one place in the Android tree).
qml.files = qml
qml.path = /usr/share/$$TARGET
INSTALLS += qml

# Rasterised PNG launcher icons at the harbour sizes (generated by make-icons.py).
# Each is named harbour-metascrub.png in a per-size dir so the .desktop's
# Icon=harbour-metascrub resolves the right one through the hicolor theme. The
# install targets are deliberately NOT named `icon`: CONFIG += sailfishapp defines
# its own `icon` target, and a same-named target is silently overridden.
icon86.files  = icons/86x86/harbour-metascrub.png
icon86.path   = /usr/share/icons/hicolor/86x86/apps
icon108.files = icons/108x108/harbour-metascrub.png
icon108.path  = /usr/share/icons/hicolor/108x108/apps
icon128.files = icons/128x128/harbour-metascrub.png
icon128.path  = /usr/share/icons/hicolor/128x128/apps
icon172.files = icons/172x172/harbour-metascrub.png
icon172.path  = /usr/share/icons/hicolor/172x172/apps
INSTALLS += icon86 icon108 icon128 icon172
